import WebSocket from 'ws';
import { SessionManager } from './sessionManager.js';
import { AuthenticationService } from './authentication.js';
import {
  IncomingMessage,
  ControlEventMessage,
  AgentRegisterMessage,
  ControllerRegisterMessage,
  ControlStopMessage,
  ServerMessage,
  PongMessage,
} from './types.js';

export class MessageRouter {
  constructor(
    private readonly sessionManager: SessionManager,
    private readonly authService: AuthenticationService
  ) {}

  /**
   * ------------------------------------------------------------
   * ROUTE INCOMING MESSAGE
   * ------------------------------------------------------------
   */
  async routeMessage(
    ws: WebSocket,
    data: string,
    isAgent: boolean
  ): Promise<void> {
    try {
      const message =
        JSON.parse(data) as IncomingMessage;

      if (
        !message ||
        typeof message !== 'object' ||
        !('type' in message)
      ) {
        this.sendError(
          ws,
          'INVALID_MESSAGE',
          'Missing message type'
        );

        return;
      }

      switch (message.type) {
        case 'AGENT_REGISTER':
          this.handleAgentRegister(
            ws,
            message
          );
          return;

        case 'CONTROLLER_REGISTER':
          this.handleControllerRegister(
            ws,
            message
          );
          return;

        case 'CONTROL_EVENT':
          this.handleControlEvent(
            ws,
            message,
            isAgent
          );
          return;

        case 'CONTROL_STOP':
          this.handleControlStop(
            ws,
            message
          );
          return;

        case 'PING':
          this.handlePing(
            ws,
            message.timestamp
          );
          return;

        default:
          console.warn(
            '[MessageRouter] Unknown message type:',
            (message as any).type
          );

          this.sendError(
            ws,
            'INVALID_MESSAGE',
            'Unsupported message type'
          );
      }
    } catch (err) {
      console.error(
        '[MessageRouter] Failed to parse/route message:',
        err
      );

      this.sendError(
        ws,
        'INVALID_MESSAGE',
        'Malformed JSON message'
      );
    }
  }

  /**
   * ------------------------------------------------------------
   * AGENT REGISTER
   * ------------------------------------------------------------
   *
   * Customer Electron Agent must register first.
   *
   * This creates the relay-side session if needed.
   */
  private handleAgentRegister(
    ws: WebSocket,
    message: AgentRegisterMessage
  ): void {
    const {
      remoteSessionId,
      meetingId,
      customerId,
      token,
    } = message;

    if (
      !remoteSessionId ||
      !meetingId ||
      !customerId ||
      !token
    ) {
      this.sendError(
        ws,
        'INVALID_MESSAGE',
        'Missing Agent registration fields'
      );

      return;
    }

    /**
     * Validate HMAC token generated by Render.
     */
    if (
      !this.authService.validateAgentToken(
        token,
        remoteSessionId,
        customerId,
        meetingId
      )
    ) {
      console.warn(
        '[MessageRouter] Agent registration failed: invalid token'
      );

      this.sendError(
        ws,
        'INVALID_TOKEN',
        'Invalid or expired Agent token'
      );

      this.safeClose(
        ws,
        1008,
        'Invalid token'
      );

      return;
    }

    /**
     * Agent registration is allowed to create the
     * in-memory relay session.
     */
    let session =
      this.sessionManager.getSession(
        remoteSessionId
      );

    if (!session) {
      try {
        session =
          this.sessionManager.createSession(
            remoteSessionId,
            meetingId,
            customerId
          );
      } catch (err) {
        console.error(
          '[MessageRouter] Failed to create relay session:',
          err
        );

        this.sendError(
          ws,
          'UNAUTHORIZED',
          'Unable to create relay session'
        );

        return;
      }
    }

    /**
     * Verify immutable session identity.
     */
    if (
      session.meetingId !== meetingId ||
      session.customerId !== customerId
    ) {
      console.warn(
        '[MessageRouter] Agent registration rejected: session identity mismatch'
      );

      this.sendError(
        ws,
        'UNAUTHORIZED',
        'Session does not belong to this Customer'
      );

      this.safeClose(
        ws,
        1008,
        'Unauthorized'
      );

      return;
    }

    if (
      !this.sessionManager.registerAgent(
        remoteSessionId,
        ws
      )
    ) {
      this.sendError(
        ws,
        'SESSION_EXPIRED',
        'Remote session is unavailable'
      );

      this.safeClose(
        ws,
        1008,
        'Session expired'
      );

      return;
    }

    const response: ServerMessage = {
      type: 'AGENT_REGISTERED',
      remoteSessionId,
    };

    this.safeSend(
      ws,
      response
    );

    console.log(
      `[MessageRouter] Agent registered successfully: ${remoteSessionId}`
    );

    /**
     * If Controller happened to register already
     * and both sides are now ready, activate control.
     *
     * Normally Agent should register first, but this
     * makes the server resilient.
     */
    this.tryActivateControl(
      remoteSessionId
    );
  }

  /**
   * ------------------------------------------------------------
   * CONTROLLER REGISTER
   * ------------------------------------------------------------
   *
   * Officer / Advisor Browser registers after Customer approval.
   */
  private handleControllerRegister(
    ws: WebSocket,
    message: ControllerRegisterMessage
  ): void {
    const {
      remoteSessionId,
      meetingId,
      controllerId,
      controllerRole,
      token,
    } = message;

    if (
      !remoteSessionId ||
      !meetingId ||
      !controllerId ||
      !controllerRole ||
      !token
    ) {
      this.sendError(
        ws,
        'INVALID_MESSAGE',
        'Missing Controller registration fields'
      );

      return;
    }

    /**
     * Validate short-lived signed Controller token.
     */
    if (
      !this.authService.validateControllerToken(
        token,
        remoteSessionId,
        controllerId,
        controllerRole,
        meetingId
      )
    ) {
      console.warn(
        '[MessageRouter] Controller registration failed: invalid token'
      );

      this.sendError(
        ws,
        'INVALID_TOKEN',
        'Invalid or expired Controller token'
      );

      this.safeClose(
        ws,
        1008,
        'Invalid token'
      );

      return;
    }

    /**
     * Agent should already have created this session.
     */
    const session =
      this.sessionManager.getSession(
        remoteSessionId
      );

    if (!session) {
      console.warn(
        '[MessageRouter] Controller registration failed: Agent session not found'
      );

      this.sendError(
        ws,
        'SESSION_EXPIRED',
        'Customer Agent has not registered this session'
      );

      return;
    }

    if (
      session.meetingId !== meetingId
    ) {
      console.warn(
        '[MessageRouter] Controller registration failed: meeting mismatch'
      );

      this.sendError(
        ws,
        'UNAUTHORIZED',
        'Meeting mismatch'
      );

      this.safeClose(
        ws,
        1008,
        'Unauthorized'
      );

      return;
    }

    /**
     * Only one controller at a time.
     */
    if (
      session.controllerId &&
      session.controllerId !==
        controllerId
    ) {
      const response: ServerMessage = {
        type: 'CONTROL_DENIED',
        reason:
          'Another participant currently has control',
        remoteSessionId,
      };

      this.safeSend(
        ws,
        response
      );

      return;
    }

    if (
      !this.sessionManager.registerController(
        remoteSessionId,
        controllerId,
        controllerRole,
        ws
      )
    ) {
      this.sendError(
        ws,
        'CONTROL_DENIED',
        'Unable to register Controller'
      );

      return;
    }

    /**
     * IMPORTANT:
     *
     * Do not just register the controller.
     *
     * We must activate control only when:
     *
     * Agent connected
     * +
     * Controller connected
     */
    const activated =
      this.sessionManager.approveControl(
        remoteSessionId
      );

    if (!activated) {
      /**
       * Most likely Agent is not connected yet.
       */
      console.warn(
        `[MessageRouter] Controller registered but session not ready: ${remoteSessionId}`
      );

      this.sendError(
        ws,
        'CONTROL_DENIED',
        'Customer Agent is not connected'
      );

      return;
    }

    const response: ServerMessage = {
      type: 'CONTROLLER_REGISTERED',
      remoteSessionId,
    };

    this.safeSend(
      ws,
      response
    );

    console.log(
      `[MessageRouter] Controller registered and control activated: ${remoteSessionId} (${controllerRole})`
    );
  }

  /**
   * ------------------------------------------------------------
   * TRY ACTIVATE CONTROL
   * ------------------------------------------------------------
   */
  private tryActivateControl(
    remoteSessionId: string
  ): void {
    if (
      !this.sessionManager.isSessionReady(
        remoteSessionId
      )
    ) {
      return;
    }

    const session =
      this.sessionManager.getSession(
        remoteSessionId
      );

    if (!session) return;

    const activated =
      this.sessionManager.approveControl(
        remoteSessionId
      );

    if (!activated) return;

    /**
     * If Controller is already waiting, notify it.
     */
    if (
      session.controllerSocket &&
      session.controllerSocket.readyState ===
        WebSocket.OPEN
    ) {
      const response: ServerMessage = {
        type: 'CONTROLLER_REGISTERED',
        remoteSessionId,
      };

      this.safeSend(
        session.controllerSocket,
        response
      );
    }
  }

  /**
   * ------------------------------------------------------------
   * CONTROL EVENT
   * ------------------------------------------------------------
   *
   * Officer / Advisor:
   *
   * CONTROL_EVENT
   *      ↓
   * Render
   *      ↓
   * Customer Agent
   */
  private handleControlEvent(
    ws: WebSocket,
    message: ControlEventMessage,
    isAgent: boolean
  ): void {
    const {
      remoteSessionId,
      event,
    } = message;

    if (isAgent) {
      console.warn(
        '[MessageRouter] Agent attempted to send CONTROL_EVENT'
      );

      this.sendError(
        ws,
        'UNAUTHORIZED',
        'Only Controller may send input'
      );

      return;
    }

    const session =
      this.sessionManager.getSession(
        remoteSessionId
      );

    if (!session) {
      this.sendError(
        ws,
        'SESSION_EXPIRED',
        'Remote session not found'
      );

      return;
    }

    if (
      !this.sessionManager.isControlAllowed(
        remoteSessionId
      )
    ) {
      this.sendError(
        ws,
        'CONTROL_DENIED',
        'Remote control is not active'
      );

      return;
    }

    if (
      session.controllerSocket !== ws
    ) {
      console.warn(
        '[MessageRouter] Controller socket mismatch'
      );

      this.sendError(
        ws,
        'UNAUTHORIZED',
        'Controller socket mismatch'
      );

      return;
    }

    if (
      !this.validateControlEvent(event)
    ) {
      this.sendError(
        ws,
        'INVALID_MESSAGE',
        'Invalid remote input event'
      );

      return;
    }

    const agentSocket =
      this.sessionManager.getAgentSocket(
        remoteSessionId
      );

    if (
      !agentSocket ||
      agentSocket.readyState !==
        WebSocket.OPEN
    ) {
      this.sendError(
        ws,
        'CONTROL_DENIED',
        'Customer Agent disconnected'
      );

      return;
    }

    /**
     * Send ONLY the inner input event to Electron Agent.
     *
     * Agent already listens for:
     *
     * MOUSE_MOVE
     * MOUSE_CLICK
     * KEY_DOWN
     * etc.
     */
    try {
      console.log(
        `[MessageRouter] Forwarding ${event.type} to agent for session ${remoteSessionId}`
      );
      agentSocket.send(
        JSON.stringify(event)
      );

      this.sessionManager.updateHeartbeat(
        remoteSessionId
      );
    } catch (err) {
      console.error(
        '[MessageRouter] Failed forwarding control event:',
        err
      );

      this.sendError(
        ws,
        'CONTROL_DENIED',
        'Unable to reach Customer Agent'
      );

      return;
    }

    /**
     * Avoid logging actual key content.
     */
    console.log(
      `[MessageRouter] Forwarded control event: ${remoteSessionId} (${event.type})`
    );
  }

  /**
   * ------------------------------------------------------------
   * CONTROL STOP
   * ------------------------------------------------------------
   */
  private handleControlStop(
    ws: WebSocket,
    message: ControlStopMessage
  ): void {
    const {
      remoteSessionId,
      reason,
    } = message;

    const session =
      this.sessionManager.getSession(
        remoteSessionId
      );

    if (!session) {
      console.warn(
        `[MessageRouter] CONTROL_STOP ignored; session not found: ${remoteSessionId}`
      );

      return;
    }

    /**
     * Preserve sockets before SessionManager clears
     * controller ownership.
     */
    const agentSocket =
      session.agentSocket;

    const controllerSocket =
      session.controllerSocket;

    this.sessionManager.stopControl(
      remoteSessionId
    );

    const stopMessage: ServerMessage = {
      type: 'CONTROL_STOPPED',
      reason,
      remoteSessionId,
    };

    /**
     * Notify Agent unless Agent itself sent stop.
     */
    if (
      agentSocket &&
      agentSocket !== ws &&
      agentSocket.readyState ===
        WebSocket.OPEN
    ) {
      this.safeSend(
        agentSocket,
        stopMessage
      );
    }

    /**
     * Notify Controller unless Controller itself sent stop.
     */
    if (
      controllerSocket &&
      controllerSocket !== ws &&
      controllerSocket.readyState ===
        WebSocket.OPEN
    ) {
      this.safeSend(
        controllerSocket,
        stopMessage
      );
    }

    console.log(
      `[MessageRouter] Control stopped: ${remoteSessionId} (${reason})`
    );
  }

  /**
   * ------------------------------------------------------------
   * APPLICATION HEARTBEAT
   * ------------------------------------------------------------
   */
  private handlePing(
    ws: WebSocket,
    timestamp: number
  ): void {
    const pong: PongMessage = {
      type: 'PONG',
      timestamp:
        typeof timestamp === 'number'
          ? timestamp
          : Date.now(),
    };

    this.safeSend(
      ws,
      pong
    );
  }

  /**
   * ------------------------------------------------------------
   * INPUT VALIDATION
   * ------------------------------------------------------------
   */
  private validateControlEvent(
    event: ControlEventMessage['event']
  ): boolean {
    if (
      !event ||
      typeof event !== 'object'
    ) {
      return false;
    }

    const validTypes = [
      'MOUSE_MOVE',
      'MOUSE_DOWN',
      'MOUSE_UP',
      'MOUSE_CLICK',
      'MOUSE_DOUBLE_CLICK',
      'SCROLL',
      'KEY_DOWN',
      'KEY_UP',
    ];

    if (
      !validTypes.includes(event.type)
    ) {
      return false;
    }

    /**
     * Mouse coordinates.
     */
    if (
      event.type === 'MOUSE_MOVE' ||
      event.type === 'MOUSE_CLICK' ||
      event.type ===
        'MOUSE_DOUBLE_CLICK'
    ) {
      if (
        typeof event.x !== 'number' ||
        typeof event.y !== 'number'
      ) {
        return false;
      }

      if (
        !Number.isFinite(event.x) ||
        !Number.isFinite(event.y)
      ) {
        return false;
      }

      if (
        event.x < 0 ||
        event.x > 1 ||
        event.y < 0 ||
        event.y > 1
      ) {
        return false;
      }
    }

    /**
     * Mouse button validation.
     */
    if (
      event.type === 'MOUSE_CLICK' ||
      event.type === 'MOUSE_DOWN' ||
      event.type === 'MOUSE_UP'
    ) {
      if (
        event.button &&
        ![
          'left',
          'right',
          'middle',
        ].includes(event.button)
      ) {
        return false;
      }
    }

    /**
     * Scroll validation.
     */
    if (
      event.type === 'SCROLL'
    ) {
      if (
        typeof event.deltaY !==
          'number' ||
        !Number.isFinite(
          event.deltaY
        )
      ) {
        return false;
      }
    }

    /**
     * Keyboard validation.
     */
    if (
      event.type === 'KEY_DOWN' ||
      event.type === 'KEY_UP'
    ) {
      if (
        typeof event.code !==
          'string' ||
        event.code.length === 0 ||
        event.code.length > 64
      ) {
        return false;
      }

      /**
       * KeyboardEvent.code examples:
       *
       * KeyA
       * Digit1
       * Enter
       * ArrowLeft
       * Backspace
       * Space
       *
       * Allow common browser code format.
       */
      if (
        !/^[A-Za-z0-9]+$/.test(
          event.code
        )
      ) {
        return false;
      }
    }

    return true;
  }

  /**
   * ------------------------------------------------------------
   * SAFE SEND
   * ------------------------------------------------------------
   */
  private safeSend(
    ws: WebSocket,
    message: object
  ): void {
    if (
      ws.readyState !==
      WebSocket.OPEN
    ) {
      return;
    }

    try {
      ws.send(
        JSON.stringify(message)
      );
    } catch (err) {
      console.error(
        '[MessageRouter] Failed to send message:',
        err
      );
    }
  }

  /**
   * ------------------------------------------------------------
   * ERROR RESPONSE
   * ------------------------------------------------------------
   */
  private sendError(
    ws: WebSocket,
    type:
      | 'CONTROL_DENIED'
      | 'SESSION_EXPIRED'
      | 'INVALID_TOKEN'
      | 'UNAUTHORIZED'
      | 'INVALID_MESSAGE',
    reason?: string
  ): void {
    /**
     * INVALID_MESSAGE isn't part of the public ServerMessage
     * union yet, so use a plain transport object here.
     */
    const response = {
      type,
      reason,
    };

    this.safeSend(
      ws,
      response
    );
  }

  /**
   * ------------------------------------------------------------
   * SAFE CLOSE
   * ------------------------------------------------------------
   */
  private safeClose(
    ws: WebSocket,
    code: number,
    reason: string
  ): void {
    try {
      if (
        ws.readyState ===
          WebSocket.OPEN ||
        ws.readyState ===
          WebSocket.CONNECTING
      ) {
        ws.close(
          code,
          reason
        );
      }
    } catch {
      // Ignore close errors.
    }
  }
}