import WebSocket from 'ws';

/**
 * Controller roles used by the actual application.
 *
 * IMPORTANT:
 * The main InsuranceOne application uses:
 * - customer
 * - officer
 * - advisor
 *
 * Do NOT use "adviser" anywhere in the relay protocol.
 */
export type ControllerRole = 'officer' | 'advisor';

/**
 * Active in-memory remote-control session stored by the Render relay.
 *
 * This is NOT the Supabase remote_control_sessions row.
 *
 * The relay session exists only while remote assistance is active.
 */
export interface ActiveRemoteSession {
  remoteSessionId: string;
  meetingId: string;
  customerId: string;

  controllerId: string | null;
  controllerRole: ControllerRole | null;

  agentSocket: WebSocket | null;
  controllerSocket: WebSocket | null;

  /**
   * False until:
   *
   * 1. Customer approves control
   * 2. Agent is registered
   * 3. Controller is registered
   *
   * MessageRouter / SessionManager will set this to true.
   */
  controlAllowed: boolean;

  expiresAt: number;
  createdAt: number;
  lastHeartbeat: number;
}

/**
 * Customer Electron Agent registration message.
 *
 * Sent:
 *
 * Customer Agent
 *      ↓
 * Render Relay
 */
export interface AgentRegisterMessage {
  type: 'AGENT_REGISTER';

  meetingId: string;
  remoteSessionId: string;

  customerId: string;

  /**
   * Short-lived HMAC signed token generated by Render.
   */
  token: string;
}

/**
 * Officer / Advisor browser registration message.
 *
 * Sent:
 *
 * Officer / Advisor Browser
 *          ↓
 * Render Relay
 */
export interface ControllerRegisterMessage {
  type: 'CONTROLLER_REGISTER';

  meetingId: string;
  remoteSessionId: string;

  controllerId: string;
  controllerRole: ControllerRole;

  /**
   * Short-lived HMAC signed token generated by Render.
   */
  token: string;
}

/**
 * Individual input event generated from SharedScreenView.
 */
export interface RemoteInputEvent {
  type:
    | 'MOUSE_MOVE'
    | 'MOUSE_DOWN'
    | 'MOUSE_UP'
    | 'MOUSE_CLICK'
    | 'MOUSE_DOUBLE_CLICK'
    | 'SCROLL'
    | 'KEY_DOWN'
    | 'KEY_UP';

  /**
   * Normalized mouse coordinates.
   *
   * Expected range:
   * 0.0 - 1.0
   */
  x?: number;
  y?: number;

  button?: 'left' | 'right' | 'middle';

  /**
   * KeyboardEvent.code
   *
   * Examples:
   * KeyA
   * Digit1
   * Enter
   * Backspace
   */
  code?: string;

  /**
   * Optional KeyboardEvent.key.
   *
   * Can be used later by the Agent if needed.
   */
  key?: string;

  deltaY?: number;

  /**
   * Optional modifier keys.
   */
  ctrlKey?: boolean;
  shiftKey?: boolean;
  altKey?: boolean;
  metaKey?: boolean;

  timestamp?: number;
}

/**
 * Browser → Render wrapper for mouse / keyboard input.
 *
 * IMPORTANT:
 *
 * Do NOT send MOUSE_MOVE directly as the WebSocket root message.
 *
 * Correct:
 *
 * {
 *   type: "CONTROL_EVENT",
 *   remoteSessionId: "...",
 *   event: {
 *     type: "MOUSE_MOVE",
 *     x: 0.5,
 *     y: 0.5
 *   }
 * }
 */
export interface ControlEventMessage {
  type: 'CONTROL_EVENT';

  remoteSessionId: string;

  event: RemoteInputEvent;
}

/**
 * Stop an active remote-control session.
 */
export interface ControlStopMessage {
  type: 'CONTROL_STOP';

  remoteSessionId: string;

  reason:
    | 'customer_stopped'
    | 'controller_released'
    | 'screen_share_stopped'
    | 'session_expired'
    | 'agent_disconnected'
    | 'controller_disconnected'
    | 'meeting_ended'
    | 'disconnect'
    | 'stopped';
}

/**
 * Browser / Agent application heartbeat.
 *
 * WebSocket ping/pong can still be used separately at the transport level.
 */
export interface PingMessage {
  type: 'PING';
  timestamp: number;
}

export interface PongMessage {
  type: 'PONG';
  timestamp: number;
}

/**
 * Request body for the Render authorization endpoint.
 *
 * POST /remote-control/authorize
 *
 * Customer calls this AFTER approving a control request.
 */
export interface AuthorizeRemoteControlRequest {
  remoteSessionId: string;
  meetingId: string;

  customerId: string;

  controllerId: string;
  controllerRole: ControllerRole;
}

/**
 * Response returned by:
 *
 * POST /remote-control/authorize
 *
 * IMPORTANT:
 * REMOTE_SESSION_SECRET must NEVER be returned.
 */
export interface AuthorizeRemoteControlResponse {
  remoteSessionId: string;

  agentToken: string;
  controllerToken: string;

  expiresInMs: number;
}

/**
 * Messages that can be received by Render WebSocket server.
 */
export type IncomingMessage =
  | AgentRegisterMessage
  | ControllerRegisterMessage
  | ControlEventMessage
  | ControlStopMessage
  | PingMessage;

/**
 * Messages sent by Render back to Agent / Controller.
 */
export interface AgentRegisteredMessage {
  type: 'AGENT_REGISTERED';
  remoteSessionId: string;
}

export interface ControllerRegisteredMessage {
  type: 'CONTROLLER_REGISTERED';
  remoteSessionId: string;
}

export interface ControlDeniedMessage {
  type: 'CONTROL_DENIED';
  remoteSessionId?: string;
  reason?: string;
}

export interface ControlStoppedMessage {
  type: 'CONTROL_STOPPED';
  remoteSessionId: string;
  reason?: string;
}

export interface SessionExpiredMessage {
  type: 'SESSION_EXPIRED';
  remoteSessionId?: string;
  reason?: string;
}

export interface InvalidTokenMessage {
  type: 'INVALID_TOKEN';
  remoteSessionId?: string;
  reason?: string;
}

export interface UnauthorizedMessage {
  type: 'UNAUTHORIZED';
  remoteSessionId?: string;
  reason?: string;
}

/**
 * Complete Render → client message type.
 */
export type ServerMessage =
  | AgentRegisteredMessage
  | ControllerRegisteredMessage
  | ControlDeniedMessage
  | ControlStoppedMessage
  | SessionExpiredMessage
  | InvalidTokenMessage
  | UnauthorizedMessage
  | PongMessage;