/**
 * Frontend remote-control types.
 *
 * IMPORTANT:
 * Keep role names consistent with the main application:
 *
 * customer
 * officer
 * advisor
 */
export type ControllerRole = 'officer' | 'advisor';
export type RemoteControlStatus = 'idle' | 'requesting' | 'requested' | 'approved' | 'registering' | 'active' | 'rejected' | 'ended' | 'error';
/**
 * React state for remote assistance.
 */
export interface RemoteControlState {
    status: RemoteControlStatus;
    customerId: string | null;
    requesterId: string | null;
    requesterName: string | null;
    requesterRole: ControllerRole | null;
    controllerId: string | null;
    controllerName: string | null;
    controllerRole: ControllerRole | null;
    controlAllowed: boolean;
    /**
     * Render relay session ID.
     *
     * Do not confuse this with the Supabase row `id`.
     */
    remoteSessionId: string | null;
    /**
     * Supabase remote_control_sessions row ID.
     */
    databaseSessionId?: string | null;
    screenShareActive: boolean;
    /**
     * True after Customer Agent has successfully registered
     * with Render.
     */
    agentRegistered?: boolean;
    /**
     * True after Officer/Advisor controller has successfully
     * registered with Render.
     */
    controllerRegistered?: boolean;
}
/**
 * Supabase row:
 *
 * public.remote_control_sessions
 */
export interface RemoteControlSession {
    id: string;
    meeting_id: string;
    customer_id: string;
    requester_id: string;
    requester_role: ControllerRole;
    controller_id: string | null;
    status: 'requested' | 'approved' | 'active' | 'rejected' | 'ended' | 'disconnected';
    /**
     * Shared identifier used by:
     *
     * React
     * Render
     * Electron Agent
     */
    remote_session_id: string;
    /**
     * Legacy field.
     *
     * Do NOT use this for Render Agent/Controller authentication.
     *
     * Real Agent and Controller tokens are short-lived HMAC tokens
     * generated by Render /remote-control/authorize.
     */
    auth_token?: string | null;
    controller_token?: string | null;
    agent_token?: string | null;
    requested_at: string | null;
    approved_at: string | null;
    started_at: string | null;
    ended_at: string | null;
    created_at: string;
    updated_at: string;
}
/**
 * ------------------------------------------------------------
 * MEETING SIGNALING EVENTS
 * ------------------------------------------------------------
 *
 * These are sent between meeting participants.
 *
 * They are NOT direct Render relay input events.
 */
export type RemoteControlSignalType = 'REQUEST_CONTROL' | 'CONTROL_GRANTED' | 'CONTROL_REJECTED' | 'CONTROL_STOPPED';
/**
 * ------------------------------------------------------------
 * INPUT EVENTS
 * ------------------------------------------------------------
 *
 * These are generated when Officer/Advisor interacts with
 * SharedScreenView.
 */
export type RemoteInputEventType = 'MOUSE_MOVE' | 'MOUSE_DOWN' | 'MOUSE_UP' | 'MOUSE_CLICK' | 'MOUSE_DOUBLE_CLICK' | 'SCROLL' | 'KEY_DOWN' | 'KEY_UP';
/**
 * General frontend remote-control event.
 *
 * Used by:
 *
 * signaling
 * SharedScreenView input
 * WebSocket server responses
 */
export interface RemoteControlEvent {
    type: RemoteControlSignalType | RemoteInputEventType | 'CONTROL_STARTED' | 'CONTROLLER_CHANGED' | 'AGENT_REGISTERED' | 'CONTROLLER_REGISTERED' | 'CONTROL_DENIED' | 'SESSION_EXPIRED' | 'INVALID_TOKEN' | 'UNAUTHORIZED' | 'PONG';
    meetingId?: string;
    customerId?: string;
    requesterId?: string;
    requesterName?: string;
    requesterRole?: ControllerRole;
    controllerId?: string;
    controllerName?: string;
    controllerRole?: ControllerRole;
    /**
     * Render remote session ID.
     */
    remoteSessionId?: string;
    /**
     * Short-lived controller token.
     *
     * Generated only by Render.
     */
    controllerToken?: string;
    /**
     * Short-lived Customer Agent token.
     *
     * Generated only by Render.
     */
    agentToken?: string;
    reason?: string;
    timestamp?: number;
    /**
     * Normalized mouse coordinates:
     *
     * 0.0 - 1.0
     */
    x?: number;
    y?: number;
    button?: 'left' | 'right' | 'middle';
    /**
     * KeyboardEvent.code.
     *
     * Examples:
     *
     * KeyA
     * Digit1
     * Enter
     * ArrowLeft
     * Backspace
     */
    code?: string;
    key?: string;
    deltaY?: number;
    ctrlKey?: boolean;
    shiftKey?: boolean;
    altKey?: boolean;
    metaKey?: boolean;
}
/**
 * Browser → Render message:
 *
 * CONTROLLER_REGISTER
 */
export interface ControllerRegisterRelayMessage {
    type: 'CONTROLLER_REGISTER';
    remoteSessionId: string;
    meetingId: string;
    controllerId: string;
    controllerRole: ControllerRole;
    token: string;
}
/**
 * Customer Agent → Render:
 *
 * AGENT_REGISTER
 */
export interface AgentRegisterRelayMessage {
    type: 'AGENT_REGISTER';
    remoteSessionId: string;
    meetingId: string;
    customerId: string;
    token: string;
}
/**
 * Browser → Render:
 *
 * CONTROL_EVENT
 */
export interface ControlEventRelayMessage {
    type: 'CONTROL_EVENT';
    remoteSessionId: string;
    event: RemoteControlEvent;
}
/**
 * Browser / Agent → Render:
 *
 * CONTROL_STOP
 */
export interface ControlStopRelayMessage {
    type: 'CONTROL_STOP';
    remoteSessionId: string;
    reason: 'customer_stopped' | 'controller_released' | 'screen_share_stopped' | 'session_expired' | 'agent_disconnected' | 'controller_disconnected' | 'meeting_ended' | 'disconnect' | 'stopped';
}
/**
 * Render authorization response.
 */
export interface RemoteControlAuthorization {
    remoteSessionId: string;
    agentToken: string;
    controllerToken: string;
    expiresInMs: number;
}
/**
 * Local Electron Agent health.
 */
export interface AgentConnectionStatus {
    connected: boolean;
    agentVersion?: string;
    lastHeartbeat?: number;
    relayConnected?: boolean;
}
/**
 * Screen-sharing state.
 */
export interface ScreenShareState {
    active: boolean;
    screenId?: string;
    displayName?: string;
    startedAt?: number;
}
//# sourceMappingURL=remoteControl.d.ts.map